"""
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
"""

import random

print("Welcome to the Cows and Bulls Game!\n")
count = 0

def cow_bull():
    cow = 0
    bull = 0
    n1 = random.randint(1000,9999)
    n1_lst = [int(i) for i in str(n1)]
    #print(n1_lst)
    n2 = input("Enter 4 digit number and we will tell you the result:\n")
    while (len(n2) != 4 or (not n2.isdigit())):
        print("Not a 4 digit number.")
        n2 = input("Enter 4 digit number and we will tell you the result:\n")
    
    n2_lst = [int(i) for i in str(n2)]
    #print(n2_lst)

    for i in range(0,4):
            if n1_lst[i] == n2_lst[i]:
                cow += 1
            elif n1_lst[i] in n2_lst:
                bull += 1
    for i in n1_lst:
        num1 = int("".join(map(str, n1_lst)))
    for j in n2_lst:
        num2 = int("".join(map(str, n2_lst)))
    #print(num1)
    #print(num2)
    print("Computer generated random 4 digit number is: \n",num1)
    print("Your 4 digit number is: \n",num2)
    print("Cow: ", cow)
    print("Bull: ", bull)
      
cow_bull()

while input("Do you want to play again: y or q \n") == "y":
    count += 1
    cow_bull()
    
else:
    print("You played this game {0} times. Bbye..!!".format(count+1))
